// All player-visible text lives here. Switching language is a data change, not a code change.
export const STRINGS = {
  ar: {
    dir: "rtl",
    title: "حصار الملك",
    startTitle: "حصار الملك",
    startSubtitle: "دافع عن بوابة القلعة ضد موجات الغزاة الحمر",
    play: "ابدأ اللعب",
    howToPlayTitle: "كيف تلعب",
    howToDesktop: "حرّك: WASD — صوّب: الفأرة — اندفاع: مسافة — فخاخ: 1 2 3",
    howToMobile: "العصا اليسرى للحركة، اليمنى للتصويب، الأزرار السفلية للاندفاع والفخاخ",
    lang: "English",
    wave: "الموجة",
    gold: "الذهب",
    bestWave: "أفضل موجة",
    gate: "البوابة",
    king: "الملك",
    pause: "إيقاف",
    resume: "استئناف",
    restart: "إعادة المحاولة",
    quitToMenu: "القائمة الرئيسية",
    paused: "الّلعبة متوقفة",
    bossWave: "!موجة الزعيم",
    waveClear: "!تم صد الموجة",
    shopTitle: "متجر الترقيات",
    shopSubtitle: "اصرف الذهب قبل الموجة القادمة",
    nextWave: "الموجة التالية",
    reroll: "تبديل (مجاني)",
    gameOverTitle: "سقطت البوابة",
    gameOverSubtitle: "صمدت حتى الموجة",
    newBest: "!رقم قياسي جديد",
    trapSpike: "شرك أشواك",
    trapBarrel: "برميل متدحرج",
    trapTower: "برج سهام",
    trapLocked: "يُفتح بالموجة",
    dash: "اندفاع",
    upgHp: "قلب إضافي",
    upgHpDesc: "زيادة الحد الأقصى للصحة والشفاء الكامل",
    upgDmg: "سهام حادة",
    upgDmgDesc: "زيادة ضرر السهم",
    upgFireRate: "سرعة الرماية",
    upgFireRateDesc: "تقليل زمن التبريد بين الطلقات",
    upgDash: "خفة الحركة",
    upgDashDesc: "تقليل زمن تبريد الاندفاع",
    upgGate: "ترميم البوابة",
    upgGateDesc: "استعادة صحة البوابة",
    upgUnlockBarrel: "فتح: برميل متدحرج",
    upgUnlockBarrelDesc: "يتدحرج بقوة عبر مسار الأعداء ويصدمهم",
    upgUnlockTower: "فتح: برج سهام",
    upgUnlockTowerDesc: "يرمي أقرب عدو تلقائيًا لمدة محدودة",
    goldAbbrev: "ذهب",
    tapToPlace: "اضغط لوضع الفخ عند اتجاه نظرك",
    fps: "إطار/ث",
    updateAvailable: "تحديث جديد متوفر",
    updateReload: "إعادة التحميل",
  },
  en: {
    dir: "ltr",
    title: "King's Siege",
    startTitle: "King's Siege",
    startSubtitle: "Defend the gate against endless waves of raiders",
    play: "Play",
    howToPlayTitle: "How to play",
    howToDesktop: "Move: WASD — Aim: Mouse — Dash: Space — Traps: 1 2 3",
    howToMobile: "Left stick to move, right stick to aim, buttons below for dash & traps",
    lang: "العربية",
    wave: "Wave",
    gold: "Gold",
    bestWave: "Best wave",
    gate: "Gate",
    king: "King",
    pause: "Pause",
    resume: "Resume",
    restart: "Restart",
    quitToMenu: "Main menu",
    paused: "Paused",
    bossWave: "BOSS WAVE!",
    waveClear: "Wave cleared!",
    shopTitle: "Upgrade Shop",
    shopSubtitle: "Spend gold before the next wave",
    nextWave: "Next wave",
    reroll: "Reroll (free)",
    gameOverTitle: "The gate has fallen",
    gameOverSubtitle: "You held the line until wave",
    newBest: "New best!",
    trapSpike: "Spike Trap",
    trapBarrel: "Rolling Barrel",
    trapTower: "Arrow Tower",
    trapLocked: "Unlocks at wave",
    dash: "Dash",
    upgHp: "Extra Heart",
    upgHpDesc: "Increase max HP and heal fully",
    upgDmg: "Sharp Arrows",
    upgDmgDesc: "Increase arrow damage",
    upgFireRate: "Rapid Fire",
    upgFireRateDesc: "Reduce time between shots",
    upgDash: "Light Footed",
    upgDashDesc: "Reduce dash cooldown",
    upgGate: "Repair Gate",
    upgGateDesc: "Restore gate health",
    upgUnlockBarrel: "Unlock: Rolling Barrel",
    upgUnlockBarrelDesc: "Rolls hard through the enemy path, hitting everything",
    upgUnlockTower: "Unlock: Arrow Tower",
    upgUnlockTowerDesc: "Auto-fires the nearest enemy for a limited time",
    goldAbbrev: "gold",
    tapToPlace: "Tap to place trap toward your aim",
    fps: "fps",
    updateAvailable: "New update available",
    updateReload: "Reload",
  },
};

export function detectLang() {
  try {
    const saved = localStorage.getItem("ks_lang");
    if (saved === "ar" || saved === "en") return saved;
  } catch (e) {}
  return (navigator.language || "en").toLowerCase().startsWith("ar") ? "ar" : "en";
}

export function saveLang(l) {
  try { localStorage.setItem("ks_lang", l); } catch (e) {}
}
